version: '3.2'
services:
  php:
    build: ./docker/
    ports:
      - 8000:80
    restart: always
    container_name: otus_project
    volumes:
      - ./src/:/var/www/html
    networks:
      - otus_project

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - 3336:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - PHP_IDE_CONFIG="serverName=Docker"
    container_name: otus_project_db
    networks:
      - otus_project
volumes:
  pg_project:

networks:
  otus:
    driver: bridge